version: 2

sources:
    - name: restaurant_raw_data
      description: restaurant data in raw format
      database: restaurant-analytics-417114
      schema: restaurant_tables
      tables:
          - name: orders
            description: daily orders

          - name: order_details
            description: line details of each order

          - name: payments
            description: payment data of each order

          - name: stores
            description: stores in which orders are made

    - name: restaurant_silver_data
      description: aggregated and cleaned restaurant data
      database: restaurant-analytics-417114
      schema: restaurant_tables_silver
      tables:
          - name: tb_sales
            description: aggregation of cleaned order and order_details tables

          - name: tb_waiter
            description: aggregation of data for waiter

          - name: tb_item_categories
            description: consolidated item categories

    - name: weather_api_data
      description: daily data coming from weather api
      database: restaurant-analytics-417114
      schema: weather_data
      tables:
          - name: daily_temperature_rain
            description: daily temperature and rain data imported via API
