restaurant_dbt:
  outputs:
    dev_silver:
      dataset: restaurant_tables_silver
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/nicolasjonckheere22/.gcp_keys/restaurant-airflow.json
      location: EU
      method: service-account
      priority: interactive
      project: restaurant-analytics-417114
      threads: 4
      type: bigquery
      target: dev_silver
    dev_gold:
      dataset: restaurant_tables_gold
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/nicolasjonckheere22/.gcp_keys/restaurant-airflow.json
      location: EU
      method: service-account
      priority: interactive
      project: restaurant-analytics-417114
      threads: 4
      type: bigquery
      target: dev_gold
