
version: 2

models:
  - name: tb_sales
    description: "A starter dbt model"
    columns:
      - name: item_id
      - name: id_order
        description: "This is the id of the order"
        tests:
          - not_null
      - name: id_store
        description: "This is the id_store of the order"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - id_store
              - id_order

  - name: tb_waiter
    description: waiter data information
    columns:
      - name: id_waiter
        description: "the primary key"
        tests:
          - unique
<<<<<<< HEAD
          - not null

  - name: tb_item_categories
    description: consolidated item tb_item_categories
    columns:
      - name: original_category
        description: source name of the category
        tests:
          - not null
      - name: consolidated_category
        description: consolidated item category
        tests:
          - not null
=======
          - not_null
>>>>>>> 6aa94774fb8a0d71b222f0872f9c3052aaf5dda5
